name: work-1

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'build.gradle'
      - 'Dockerfile'
      - 'index.html'
    branches:
      - main

# GHCR 푸시를 위한 권한 (권장)
permissions:
  contents: read
  packages: write

jobs:
  makeTagAndRelease:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          draft: false
          prerelease: false

  buildImageAndPush:
    name: 도커 이미지 빌드와 푸시
    needs: makeTagAndRelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (선택) 진단: 파일/경로 즉시 확인
      - name: 진단 - 파일 존재 확인
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "== .github/workflows =="
          ls -la .github/workflows || true
          if [ -f ".github/workflows/Dockerfile" ]; then
            echo "✅ FOUND: .github/workflows/Dockerfile"
          else
            echo "❌ MISSING: .github/workflows/Dockerfile"
            exit 1
          fi

      - name: Docker Buildx 설치
        uses: docker/setup-buildx-action@v3

      - name: 레지스트리 로그인
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: echo "OWNER_LC=${OWNER,,}" >> "${GITHUB_ENV}"
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: 빌드 앤 푸시
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}                            # 레포 루트(절대경로)
          file:    ${{ github.workspace }}/.github/workflows/Dockerfile # ⬅️ Dockerfile 위치 명시
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/deploy:${{ needs.makeTagAndRelease.outputs.tag_name }},
            ghcr.io/${{ env.OWNER_LC }}/deploy:latest
